### PR TITLE
remove build instruction from readme

### PR DESCRIPTION
**Pull request by vbence86**

### CODE REVIEW

**Comment by jbalsas** [comment]
Merging, the rationale being we don't provide the build files and makes no sense to instruct building the code for nothing. All you can do is run the tests. 

@blzaugg, @zenorocha, we have many such components (UI and non-UI). Maybe we should start thinking about:
a) A better, more descriptive `README.md` boilerplate
b) A global place to put them (metaljs.com?)

**Comment by blzaugg** [comment]
@jbalsas, would this just be updated in https://github.com/metal/generator-metal/blob/master/app/templates/_README.md

Also, why the metaljs.com suggestion?

**Comment by jbalsas** [comment]
Hey @blzaugg, I think the template can only do as much. It is also just a set of instructions on how to build the code, but maybe we could do better. We could add screenshots of what's the expected result, documentation on how to use the components and their APIs and things like that.

The `metaljs.com` suggestion is to just try to make sense of everything in one place. Same way we are going to group the clay components in the `clacyss.com` site, we could do for `metal.js`, avoiding the need to hunt around for repos...

**Comment by blzaugg** [comment]
Got it, thanks.

**Pull request merged**
