### PR TITLE
Update metal-uri to v3.0.0

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hey @eduardolundgren,

Metal Ajax uses Metal Uri too and it has to be updated to v3.0.0 to allow Metal Ajax to work in other environments apart from Node and browsers.

Could you please get this PR and release a new version?

Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev, @Robert-Frampton was looking at applying some changes to `metal-uri` that could make the change to the `karma.conf` file unnecessary.

In the meantime, I've pushed a `develop` branch and set it as the `base` for this PR so it follows our new branching strategy (not-yet-fully-announced).

@Robert-Frampton, let us know if you think we should just merge this or wait until some upcoming changes in `metal-uri`.

**Comment by ipeychev** [comment]
That's good to know. Okay, let's see what Rob will say.

**Comment by Robert-Frampton** [comment]
Hey @jbalsas @ipeychev 

After taking a look into making those changes to `metal-uri`, I decided that I didn't really like the idea of copying all of that third party logic, in the end it would have been 4 different modules that we would have been copying into our source.

Since we got the tests running on [wedeploy/api-js](https://github.com/wedeploy/api-js/pull/205) as well, let's go ahead and merge this in. We can put a tutorial together on how to configure karma tests with projects depending on Metal at some point to help alleviate the pain.

**Comment by jbalsas** [comment]
Merged to `develop`!

**Pull request merged**
