### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, Firefox 56 failed the `Ajax Progress should track progress of ajax request` :(

**Comment by Robert-Frampton** [comment]
Weird, it passes on Firefox 56 locally for me.

**Comment by jbalsas** [comment]
Yeah, it passed in all the other branches and PRs before... I've restarted the test to be sure, might just be flaky as well :(

**Comment by jbalsas** [comment]
There... it looks like it might fail on and off. We can merge and release, and investigate later, or try before... what do you prefer?

**Comment by Robert-Frampton** [comment]
I ran these tests a bunch of times in trying to debug the previous Safari issue, and this is the only time I remember FF 56 failing, so I think it's fine to merge.

**Comment by jbalsas** [comment]
Done!

**Pull request merged**
