### PR TITLE
Updates metal-promise to 3.0.2 to ensure child promises are also instances of ProgressPromise

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by jbalsas** [comment]
Still failing on Safari9, @Robert-Frampton... feels a bit flaky... how do you want to proceed?

**Comment by Robert-Frampton** [comment]
Since it actually does work on Safari 9 part of the time, and it's a non-essential feature of `metal-ajax`, I say we just skip the test for Safari 9. By searching for Safari related ajax issues, it's apparent that ajax requests in general are flaky on older versions.

**Comment by jbalsas** [comment]
Sounds good to me!

**Comment by Robert-Frampton** [comment]
@jbalsas, looks like we're good.

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, I've just released `metal-promise@3.0.3`... should we test with that version, or would you prefer to send a followup?

**Comment by Robert-Frampton** [comment]
Might as well update it, I'll send the changes.

**Comment by Robert-Frampton** [comment]
@jbalsas, updated.

**Pull request merged**
